POST users-api-production-ff6d.up.railway.app/users
Content-Type: application/json

{
    "userName": "user teste login",
    "login": "logins",
    "password": "login123"
}

###

// 
GET users-api-production-ff6d.up.railway.app/all-users
###
POST users-api-production-ff6d.up.railway.app/login
Content-Type: application/json

{
    "login": "logins",
    "password": "login123"
}

###

GET http://localhost:5555/active-sessions
###
POST http://localhost:5555/users
Content-Type: application/json

{
   "userName": "teste login",
    "login": "logins",
    "password": "login123"
}
###
POST http://localhost:5555/users
Content-Type: application/json

{
   "userName": "magnoS",
    "login": "asdasdsasdaa",
    "password": "logiadsssdan123"
}

###

POST http://localhost:5555/login
Content-Type: application/json

{
    "login": "logins",
    "password": "login123"
}
###

POST http://localhost:5555/login
Content-Type: application/json

{
    "login": "asdasdsasdaa",
    "password": "logiadsssdan123"
}