POST users-api-production-ff6d.up.railway.app/users
Content-Type: application/json

{
    "userName": "testando",
    "login": "teste1",
    "password": "faker123"
}

###

// b87d0a81-ae4a-4a76-a743-0f1d5cbb5a65
GET http://localhost:3333/users/b87d0a81-ae4a-4a76-a743-0f1d5cbb5a65
